Foundationally, we are building arrays using the numpy library
We can use the np.array method to create the array

In [3]:
import numpy as np

In [4]:
one_dimension = np.array([1, 2, 3, 4])
print(one_dimension)

[1 2 3 4]


In [5]:
two_dimensions = np.array([[2,4,5],[7,8,9]])
print(two_dimensions)

[[2 4 5]
 [7 8 9]]


we can use np.zeros to create an array of zeros with different dimensions

In [6]:
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


we can also create a two dimensional matrix of zeros

In [7]:
zeros_two = np.zeros((5,2))
print(zeros_two)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


we can use the np.arange method to create a range of numbers
in the (), we start at the first integer and go up to but not include the second integer
so (5,10) would be the range of 5 to 9

In [8]:
range_one = np.arange(5,10) 
print(range_one)

[5 6 7 8 9]


we can also create a matrix of random numbers using the random.randint method
where low = lowest number possible, high = highest number possible, and size = the size of the array

In [9]:
random_nums = np.random.randint(low=50, high=100, size = (8))
print(random_nums)

[81 89 57 86 56 72 83 73]


we can also create an array of float numbers using the random.random() method - these numbers are between 0 and 1 


In [10]:
random_floats = np.random.random(size=(14))
print(random_floats)

[0.45520162 0.92888295 0.77645678 0.89425798 0.69066346 0.67076792
 0.96810981 0.39422219 0.70824585 0.97423442 0.77876478 0.88692671
 0.89980538 0.81378911]


we can add numbers to the randomized array 
..say we want to add the number 2 to each number in the array, so the array will have numbers between 0 and 3

In [11]:
random_floats_2 = random_floats + 2
print(random_floats_2)

[2.45520162 2.92888295 2.77645678 2.89425798 2.69066346 2.67076792
 2.96810981 2.39422219 2.70824585 2.97423442 2.77876478 2.88692671
 2.89980538 2.81378911]


and the same thing can be done with multiplication
say we want to multiple by 3 

In [12]:
random_floats_3 = random_floats * 3
print(random_floats_3)

[1.36560486 2.78664885 2.32937034 2.68277395 2.07199037 2.01230376
 2.90432942 1.18266658 2.12473755 2.92270327 2.33629433 2.66078014
 2.69941613 2.44136734]


lets make an array of random integers between 0 and 50, and then create another array multiplying those numbers by 3

In [16]:
random_integers = np.random.randint(low=0, high=50, size = 40)
random_integers_x3 = random_integers * 3
print(random_integers)
print('line')
print(random_integers_x3)

[33 12 41 29  3 19 34 33 11  3 15 49 17 34 42 34  5 23  4 25 49 48 23 41
 26  4 35  3 23 11 33  7  8 42 18 39 12  2 19 15]
line
[ 99  36 123  87   9  57 102  99  33   9  45 147  51 102 126 102  15  69
  12  75 147 144  69 123  78  12 105   9  69  33  99  21  24 126  54 117
  36   6  57  45]


Task 1:
Your goal is to create a simple dataset consisting of a single feature and a label as follows:
Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named feature.
Assign 15 values to a NumPy array named label such that:

In [20]:
feature = np.arange(6,21)
print(feature)
label = (feature * 3) + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


Task 2: To make your dataset a little more realistic, insert a little random noise into each element of the label array you already created. To be more precise, modify each value assigned to label by adding a different random floating-point value between -2 and +2.
Don't rely on broadcasting. Instead, create a noise array having the same dimension as label.

In [23]:
noise = label + np.random.random(15) + np.random.randint(low=-2, high=2, size = 15)
print(noise)

[22.30142344 23.36852819 29.69201711 30.4474863  33.5147878  38.04771485
 40.69797023 42.85527381 47.86198074 48.03146912 50.00553364 53.27849531
 57.07041905 60.26472939 65.33073746]
